# ************************************************************************
# Product    : Home information and control
# Date       : 2017-01-10
# Copyright  : Copyright (C) 2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : owserver/Dockerfile-rpi
# Version    : 0.1.0
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM resin/rpi-raspbian:latest

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apt-get update && \
    apt-get install -y vim \
                       ow-shell \
                       owserver && \
    rm -rf /var/lib/apt/lists*

COPY Configs/owfs.conf /etc/owfs.conf

EXPOSE 4304

ENTRYPOINT /usr/bin/owserver -c /etc/owfs.conf --foreground
