# ************************************************************************
# Product    : Home information and control
# Date       : 2017-01-10
# Copyright  : Copyright (C) 2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : owserver/Dockerfile-rpi
# Version    : 0.1.1
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM resin/rpi-raspbian:latest

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apt-get update && \
    apt-get install -y vim \
                       ow-shell \
                       owserver && \
    rm -rf /var/lib/apt/lists*

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_BASE_IMAGE_NAME na
ENV DOCKER_BASE_IMAGE_TAG na

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

COPY Configs/owfs.conf /etc/owfs.conf


EXPOSE 4304

ENTRYPOINT /usr/bin/owserver -c /etc/owfs.conf --foreground
